# Generated by Django 5.1.7 on 2025-04-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_seller_alter_product_quantity_orderstatusupdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('razorpay', 'Online Payment'), ('card', 'Credit/Debit Card'), ('upi', 'UPI')], default='cod', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('razorpay', 'Online Payment'), ('card', 'Credit/Debit Card'), ('upi', 'UPI')], default='cod', max_length=20),
        ),
    ]
