# Generated by Django 5.1.7 on 2025-04-24 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_amount_paid_order_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
    ]
