# Generated by Django 5.1.7 on 2025-05-18 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('issuer', models.CharField(blank=True, max_length=200)),
                ('date_obtained', models.DateField(blank=True, null=True)),
                ('certificate_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('score', models.CharField(blank=True, max_length=50)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='VC DINESH', max_length=100)),
                ('title', models.CharField(default='Software Engineer', max_length=200)),
                ('location', models.CharField(default='Bengaluru - 560103', max_length=100)),
                ('phone', models.CharField(default='9121687814', max_length=20)),
                ('email', models.EmailField(default='DINESHROYAL9121@GMAIL.COM', max_length=254)),
                ('linkedin', models.URLField(default='https://www.linkedin.com/in/dinesh-royal-4a66441b8/')),
                ('github', models.URLField(default='https://github.com/dineshroyal9121687814')),
                ('summary', models.TextField(default='Software engineer with 2+ years of experience. Executed automatic setups locally for testing and created Jenkins pipelines. Experienced in automation and UI development, with hands-on expertise in AWS, Docker, and Kubernetes, while actively expanding knowledge in DevOps practices.')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('programming', 'Programming Languages'), ('devops', 'DevOps & Cloud'), ('testing', 'Testing & Automation'), ('other', 'Other Tools')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='portfolio.experience')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/projects/')),
                ('github_url', models.URLField(blank=True, null=True)),
                ('live_url', models.URLField(blank=True, null=True)),
                ('technologies', models.ManyToManyField(related_name='projects', to='portfolio.skill')),
            ],
        ),
    ]
