env:
  RAZORPAY_KEY_ID: ${{ secrets.RAZORPAY_KEY_ID }}
  RAZORPAY_SECRET_KEY: ${{ secrets.RAZORPAY_SECRET_KEY }}


name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Connect and deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/Ecom
          git pull origin main
          echo "RAZORPAY_KEY_ID=${{ secrets.RAZORPAY_KEY_ID }}" > .env
          echo "RAZORPAY_SECRET_KEY=${{ secrets.RAZORPAY_SECRET_KEY }}" >> .env
          echo "SQLITE_PATH=/app/db.sqlite3" >> .env
          docker compose down
          docker compose up --build -d
